'use client'
import * as React from 'react'
import * as SelectPrimitive from '@radix-ui/react-select'
import { Check,ChevronDown,ChevronUp } from 'lucide-react'
import { clsx } from 'clsx'
const Select=SelectPrimitive.Root,SelectGroup=SelectPrimitive.Group,SelectValue=SelectPrimitive.Value
const SelectTrigger=React.forwardRef<React.ElementRef<typeof SelectPrimitive.Trigger>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Trigger>>(({className,children,...props},ref)=><SelectPrimitive.Trigger ref={ref} className={clsx('flex h-12 w-full items-center justify-between border-0 border-b border-[var(--loam-ink)] bg-transparent px-0 font-serif text-base outline-none transition-colors hover:border-[var(--loam-clay)] focus:border-[var(--loam-clay)] disabled:opacity-50',className)} {...props}>{children}<SelectPrimitive.Icon><ChevronDown className="size-4 transition-transform duration-300 [[data-state=open]_&]:rotate-180 motion-reduce:transition-none"/></SelectPrimitive.Icon></SelectPrimitive.Trigger>)
SelectTrigger.displayName=SelectPrimitive.Trigger.displayName
const SelectContent=React.forwardRef<React.ElementRef<typeof SelectPrimitive.Content>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Content>>(({className,children,position='popper',...props},ref)=><><style>{`@keyframes loam-select-in{from{opacity:0;transform:scaleY(.72);clip-path:inset(0 0 100% 0 round var(--loam-radius-md))}to{opacity:1;transform:scaleY(1);clip-path:inset(0 0 0 0 round var(--loam-radius-md))}}@media(prefers-reduced-motion:reduce){.loam-select-motion{animation:none!important}}`}</style><SelectPrimitive.Portal><SelectPrimitive.Content ref={ref} position={position} className={clsx('loam-select-motion relative z-50 max-h-80 w-[var(--radix-select-trigger-width)] min-w-[var(--radix-select-trigger-width)] origin-[var(--radix-select-content-transform-origin)] overflow-hidden rounded-[var(--loam-radius-md)] border border-[var(--loam-ink)] bg-[var(--loam-surface)] text-[var(--loam-ink)] shadow-[0_18px_50px_rgb(0_0_0/16%)] [animation:loam-select-in_300ms_var(--loam-ease-spring)]',position==='popper'&&'translate-y-1',className)} {...props}><SelectPrimitive.ScrollUpButton className="flex justify-center py-1"><ChevronUp className="size-4"/></SelectPrimitive.ScrollUpButton><SelectPrimitive.Viewport className="p-1">{children}</SelectPrimitive.Viewport><SelectPrimitive.ScrollDownButton className="flex justify-center py-1"><ChevronDown className="size-4"/></SelectPrimitive.ScrollDownButton></SelectPrimitive.Content></SelectPrimitive.Portal></>)
SelectContent.displayName=SelectPrimitive.Content.displayName
const SelectItem=React.forwardRef<React.ElementRef<typeof SelectPrimitive.Item>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Item>>(({className,children,...props},ref)=><SelectPrimitive.Item ref={ref} className={clsx('relative flex min-h-10 cursor-default select-none items-center rounded-[var(--loam-radius-sm)] py-2 pl-8 pr-3 font-serif text-sm outline-none data-[highlighted]:bg-[var(--loam-ink)] data-[highlighted]:text-[var(--loam-cream)] data-[disabled]:opacity-40',className)} {...props}><span className="absolute left-2"><SelectPrimitive.ItemIndicator><Check className="size-4"/></SelectPrimitive.ItemIndicator></span><SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText></SelectPrimitive.Item>)
SelectItem.displayName=SelectPrimitive.Item.displayName
const SelectLabel=({className,...props}:React.ComponentPropsWithoutRef<typeof SelectPrimitive.Label>)=><SelectPrimitive.Label className={clsx('px-3 py-2 font-mono text-[9px] uppercase tracking-[.14em] text-[var(--loam-ink-soft)]',className)} {...props}/>
const SelectSeparator=({className,...props}:React.ComponentPropsWithoutRef<typeof SelectPrimitive.Separator>)=><SelectPrimitive.Separator className={clsx('my-1 h-px bg-[var(--loam-line)]',className)} {...props}/>
export { Select,SelectGroup,SelectValue,SelectTrigger,SelectContent,SelectItem,SelectLabel,SelectSeparator }
